### ISSUE TITLE
X11 Window stuck on macOS Monterey

### ISSUE THREAD

**Issue by cnatzke** [jsmallcombe/jRootAnalysisTools#3]
Hi, 

I am running jRootAnalysisTools on a Ubuntu virtual machine on my macbook. 

When I open a new ```jEnv``` the resultant window gets stuck behind the mac top toolbar and I cannot access many of the tools. Has anyone seen this before? I suspect it's an issue with X11 or the like. 

I can move the popout to another monitor but it gets stuck in the same place, just on the new monitor. 

<img width="1440" alt="Screen Shot 2022-08-04 at 11 09 06 AM (2)" src="https://user-images.githubusercontent.com/17180596/182921019-140d560e-cc06-4e7d-ad42-1b544d84f271.png">

OS: macOS Monterey 12.5
VM OS: Ubuntu 20.04.2 LTS

**Comment by cnatzke** [comment]
If I open a TCanvas via
```
new TCanvas()
```
the window behaves as expected.

<img width="1440" alt="Screen Shot 2022-08-04 at 11 21 37 AM (2)" src="https://user-images.githubusercontent.com/17180596/182922962-0465dcba-4f4c-4a23-9ca4-96d5f5d9724a.png">

**Comment by jsmallcombe** [comment]
We have had a few mac users and I havent had this issue reported before. Meaning its probably the particular VM setup thats the issue.

There are a few things in the code that could be causing the issue, the default starting position or the slightly messy resizing+repositioning operations that happen when the sidebars open/close (which are called during initialisation). Based on that first image, which is showing an empty canvas window, which is only possible if that code isnt working properly, I guess some of that code is to blame.

Please can you replaced /src/j_env.cpp with this one and see if that fixes the issue. If it does I'll look at a more refined solution.
[j_env.zip](https://github.com/jsmallcombe/jRootAnalysisTools/files/9264680/j_env.zip)

I couldnt unpick exactly how the GUI part of TCanvas initialises. Could you instead run this minimal working example using the  TGMainFrame class and report the result.

```
TGMainFrame* GMF=new TGMainFrame(gClient->GetRoot());  
GMF->AddFrame(new TRootEmbeddedCanvas("C1",GMF,600,400));  
GMF->MapSubwindows();  
GMF->Resize(GMF->GetDefaultSize());  
GMF->MapWindow();
```

**Comment by cnatzke** [comment]
> Please can you replaced /src/j_env.cpp with this one and see if that fixes the issue. If it does I'll look at a more refined solution.

This seemed to fix the issue. The canvas opened and I could move it around without issue. 

<img width="1440" alt="Screen Shot 2022-08-05 at 1 35 38 PM (2)" src="https://user-images.githubusercontent.com/17180596/183158789-358ecb50-6c63-467f-86f4-91b9b704004f.png">

> Could you instead run this minimal working example using the TGMainFrame class and report the result.

This set of commands opened a new canvas window without issue. There was no terminal output when running the commands and the window only opened on the last command. I did try this after replacing the j_env.cpp file if that makes a difference. 

![Screen Shot 2022-08-05 at 1 37 17 PM](https://user-images.githubusercontent.com/17180596/183158971-9e86f557-2f3f-47fd-8e6d-365c5b8a4105.png)

**Comment by jsmallcombe** [comment]
Great.
Did those both open in the positions shown respectively?
Could you please run the attached script and tell me the output.

[deftest.zip](https://github.com/jsmallcombe/jRootAnalysisTools/files/9290964/deftest.zip)

**Comment by cnatzke** [comment]
In the previous screenshot I move the ```jEnv``` window to check that it behaved properly. Here is how it opened: 

![Screen Shot 2022-08-09 at 9 13 54 AM](https://user-images.githubusercontent.com/17180596/183704683-c0cfcddf-0d2f-4b11-bfdd-a6a3ce1236ae.png)
 

> Could you please run the attached script and tell me the output.

**Comment by cnatzke** [comment]
Sorry, didn't mean to close the the issue, I apparently hit the wrong set of keys. 

> Could you please run the attached script and tell me the output.

```
root [0]
Processing /home/vagrant/jRootAnalysisTools/bin/root_start.C...
root [1] .x deftest.C
LINUX
root [2]
```
