### ISSUE TITLE
Trouble installing jRootAnalysisTool

### ISSUE THREAD

**Issue by Ansil782** [jsmallcombe/jRootAnalysisTools#4]
I am tryng to install the jRoot tool but when I try and use "make" I get an error as follows:

src/j_env.cpp: In constructor ‘jEnv::jEnv()’:
src/j_env.cpp:158:5: error: ‘gVirtualX’ was not declared in this scope
  158 |     gVirtualX->TranslateCoordinates(GetId(),GetParent()->GetId(),0,0,fPixOffX,fPixOffY,wdummy);
      |     ^~~~~~~~~
src/j_env.cpp: In member function ‘void jEnv::ShowDir()’:
src/j_env.cpp:401:5: error: ‘gVirtualX’ was not declared in this scope
  401 |     gVirtualX->TranslateCoordinates(GetId(),GetParent()->GetId(),0,0,x,y,wdummy);
      |     ^~~~~~~~~
src/j_env.cpp: In member function ‘void jEnv::HideDir()’:
src/j_env.cpp:417:5: error: ‘gVirtualX’ was not declared in this scope
  417 |     gVirtualX->TranslateCoordinates(GetId(),GetParent()->GetId(),0,0,x,y,wdummy);
      |     ^~~~~~~~~
make: *** [Makefile:45: bin/build/j_env.o] Error 1

I have Root 26.8 and I do source the thisis.sh file before using make but it still gives me an error regarding gVirtualX.

**Comment by jsmallcombe** [comment]
What OS are you using? Had some trouble with this and macs.
Edit src/j_env.cpp and comment out the 2 parts between #if __linux__ and #endif at lines 398 and 414
Recompile and test.
