### ISSUE TITLE
twin gaus fit via command line issue

### ISSUE THREAD

**Issue by Spagnole** [jsmallcombe/jRootAnalysisTools#6]
I have been doing some fitting using the command line for a script.
I tried to fit some peaks using a twin gaussian function by setting PeakType=2.
This does not set a twin gauss fit.
Looking at the j_ultrapeakfit.cpp file the condition for setting a twin gaus fit

bool twogaus=((int)(peaktype/10)%2); 
If you give the value two it will return 0.

I have gotten around this issue by setting peaktype=10 in my fit so that 'bool twogaus' will return 1.

FullFitHolder* fitA = Ultrapeak::PeakFit(hist,FitRangeStart,FitRangeEnd,fInput,BackgroundMode,PeakType,0,SigmaParameter,DecayParameter,SharingParameter)

**Comment by jsmallcombe** [comment]
Thank you for the report and tracking down the source.
It looks like its just the documentation that is wrong, I didnt update it correctly after a big overhaul of fitting function in the previous release.
peaktype=10  and peaktype=11 should be used for twingaus with and without a tail respectively. 
I have updated the docs and created an overdue new release
