### ISSUE TITLE
Installing v3.1 on Macbook

### ISSUE THREAD

**Issue by Noor999000** [jsmallcombe/jRootAnalysisTools#7]
Hi,

When I was compiling the latest version I got an error associated with j_X11paste.cxx, which was easily fixed by 

by changing these lines 

```
#if defined __APPLE__

#elif defined __linux__
```

with 

`#ifdef __linux__
`

**Comment by jsmallcombe** [comment]
Hi,
Thank you reporting the error and dermining a potential work around.
I am concerned with that solution that people running linux environments within mac could potentially end up with undesirable behaviour. Could you test this alternate code for me?
```
#if defined __APPLE__

int dummy = 1;

#elif defined __linux__
```

**Comment by Noor999000** [comment]
I tried but it failed 

> 2 warnings generated.
> Undefined symbols for architecture arm64:
>   "ReadX11CopyBufferAsText(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char>>&, bool)", referenced from:
>       CopyBufferToVectors(ClipboardBufferVectors&, bool) in j_clipboard_parse.o
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [bin/libJanalysistools.so] Error 1

**Comment by jsmallcombe** [comment]
Thanks for checking, I see my mistake.
Could you please try the following? If this doesnt work I'll push your original fix.

 `#if defined(__linux__) && !defined(__APPLE__)`

**Comment by Noor999000** [comment]
it worked

**Comment by jsmallcombe** [comment]
Great. Thank you.
